M48
; DRILL file {KiCad 9.0.3} date 2026-05-24T18:29:38+0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-24T18:29:38+06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X126.25Y-70.75
X126.25Y-75.75
T2
X92.04Y-68.6
X92.04Y-71.6
T3
X93.25Y-62.5
X93.25Y-87.5
X128.25Y-62.5
X128.25Y-87.5
M30
